name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      EMBEDDING_PROVIDER: ${{ secrets.EMBEDDING_PROVIDER }}
      EMBEDDING_API_KEY: ${{ secrets.EMBEDDING_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Debug Environment Variables
        run: |
          echo "Embedding Provider: $EMBEDDING_PROVIDER"
          echo "API Key Length: ${#EMBEDDING_API_KEY}"
        env:
          EMBEDDING_API_KEY: ${{ secrets.EMBEDDING_API_KEY }}

      - name: Run tests
        run: npm test
