name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: mongodb://localhost:27017/test
      EMBEDDING_PROVIDER: openai
      EMBEDDING_API_KEY: test-key-123
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm test